### ISSUE TITLE
error compiling server

### ISSUE THREAD

**Issue by dimalukas** [mrfoe7/quic-example#1]
"github.com/lucas-clemente/quic-go/quictrace"
this import does not exists in that package and there is no Server field in the http3 Server struct.
Also there is no QuickTracer field in the "&quic.Config{QuicTracer: tracer}".
![error_server_http3](https://user-images.githubusercontent.com/7952328/185066946-fa514edd-89ec-41d9-914d-bb5e0a027ddd.png)
![error_quic_tracer](https://user-images.githubusercontent.com/7952328/185066962-29ef8828-e681-41a2-b0d4-9bfd5672fa84.png)

**Comment by sshaplygin** [comment]
Hey, @dimalukas More thx for first issue. Feedback important for me. I have updated this source code. Pls, loop updates

**Comment by sshaplygin** [comment]
Updates https://github.com/sshaplygin/quic-example/pull/2
